### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by hiagop** [gonum/netlib#15]
Trying to install the netlib packages following the instructions shown in the README file gives [this errors](https://pastebin.com/aEKk7TXx), just as I `go get gonum.org/v1/netlib/...`

Is there anything else needed to make this work?

**Comment by kortschak** [comment]
Prefix that command with and appropriate set of env vars: `CGO_LDFLAGS="-L/path/to/OpenBLAS -lopenblas" go get gonum.org/v1/netlib/...`.

**Comment by hiagop** [comment]
That's embarassing, but I've tries that already.
Here what I've got:
```
# gonum.org/v1/netlib/blas/netlib
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
# gonum.org/v1/netlib/lapack/lapacke
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
```
The compilation process succeded though, but I had no sign of any file named `openblas` inside the cloned repository.

**Comment by kortschak** [comment]
This repository does not provide OpenBLAS, you will need to either install it from your operating system's package manager or [from source](https://github.com/xianyi/OpenBLAS). Is there a reason you are not just using the Go-native BLAS/LAPACK implementations?

**Comment by hiagop** [comment]
@kortschak I know where to get the source files from. That was the compilation process I was talking about. Actually I thought this library were necessary for the whole thing to work. The documentation says the native version is not finished yet. 
I'll try using the unfinished Go library anyway.
Thank you for the attention, though.
Sorry for the incovenience.

You may close this issue.

**Comment by kortschak** [comment]
The package here does not build OpenBLAS, it is a wrapper to Any™ C BLAS or LAPACKE implementation, so you need to follow the build instructions for the C implementation you choose - we have found OpenBLAS to work well.

The [Gonum BLAS implementation](https://godoc.org/gonum.org/v1/gonum/blas/gonum) is complete for real matrices and the complex matrix implementation is being done at the moment. The [LAPACK implementation is good](https://godoc.org/gonum.org/v1/gonum/lapack/gonum); a complete LAPACK implementation is a very big undertaking and so we implement what we need or there is interest in (preferably backed by a preparation to contribute).
