### ISSUE TITLE
blas,lapack: rename to netilb

### ISSUE THREAD

**Issue by btracey** [gonum/netlib#5]
"gonum.org/v1/netlib/blas" => "gonum.org/v1/netlib/blas/netlib"  and
"gonum.org/v1/netlib/lapack" => "gonum.org/v1/netlib/blas/lapack"

See
 https://github.com/gonum/gonum/issues/33 and https://github.com/gonum/gonum/pull/26#issuecomment-304746389

**Comment by kortschak** [comment]
"gonum.org/v1/netlib/blas" => "gonum.org/v1/netlib/blas/netlib" and
"gonum.org/v1/netlib/lapack" => "gonum.org/v1/netlib/lapack/netlib"

**Comment by btracey** [comment]
Whoops. Thanks.
