### ISSUE TITLE
Unable to get the package

### ISSUE THREAD

**Issue by kushthedude** [gonum/netlib#74]
### What did you do?

`go get gonum.org/v1/netlib@v0.0.0-20190331212654-76723241ea4e`

### What did you expect to happen?

Package should be grepped.

### What actually happened?

```sh
	gonum.org/v1/netlib@v0.0.0-20190331212654-76723241ea4e requires
7
	modernc.org/cc@v1.0.0: reading modernc.org/cc/go.mod at revision v1.0.0: unknown revision v1.0.0
8
##[error]Process completed with exit code 1.
```

### Does this issue reproduce with the current master?

Yes

**Comment by kushthedude** [comment]
cc: @vladimir-ch Can you please take a look at the error, our CI actions are failing due to this ? Link to the CI error logs https://github.com/layer5io/meshery/pull/988/checks?check_run_id=660466720

**Comment by sbinet** [comment]
It seems to me gitlab (where modernc.org/... is hosted) is going through some maintenance work. (See the post on golang-nuts)

**Comment by kortschak** [comment]
Note that using the Go proxy in your builds would avoid this problem.

**Comment by kushthedude** [comment]
Thanks for the quick response @kortschak @sbinet !
