### ISSUE TITLE
netlib/blas: adapting to upstream change of CBLAS_INDEX

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/netlib#86]
In https://github.com/Reference-LAPACK/lapack/pull/588 the reference CBLAS changed the definition of CBLAS_INDEX from int to size_t. Should we update cblas.h to the latest upstream version and so adopt this change?

**Comment by kortschak** [comment]
I think that's reasonable so long as it doesn't break things. Has OpenBLAS made that change?

**Comment by vladimir-ch** [comment]
It seems that OpenBLAS has been using `#define CBLAS_INDEX size_t` for more than 10 years so it's the reference catching up to what other BLAS implementations do.

**Comment by kortschak** [comment]
Great, then that seems like the thing to do.

**Comment by vladimir-ch** [comment]
Then the question arises what type should the `I?amax` routines return. Most naturally it should be `uint` which means changing our Level1 interfaces. However, if that is done, then`I?amax`could not return -1 as an invalid index in case of a negative increment or zero size. So either we look away and keep returning `int` or we panic instead of returning -1. Any other idea?

**Comment by kortschak** [comment]
I think we keep out signature the same. The internal representation of the index/size type isn't really our concern beyond making sure that it is big enough.

What does OpanBLAS do for `I?amax`?
